### PR TITLE
use get_expr rather than get_expr1

### LINKED ISSUE #713: 'julia/getModuleAt' sometimes fails with MethodError
```
┌ Warning: Some Julia code in the VS Code extension crashed with
│   e =
│    MethodError: no method matching parentof(::Nothing)
│    Closest candidates are:
│      parentof(!Matched::StaticLint.Scope) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/StaticLint/src/scope.jl:92
│      parentof(!Matched::CSTParser.EXPR) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/CSTParser/src/spec.jl:294
└ @ Main ~/Documents/Git/julia-vscode/scripts/error_handler.jl:5
ERROR: MethodError: no method matching parentof(::Nothing)
Closest candidates are:
  parentof(!Matched::StaticLint.Scope) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/StaticLint/src/scope.jl:92
  parentof(!Matched::CSTParser.EXPR) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/CSTParser/src/spec.jl:294
Stacktrace:
 [1] retrieve_scope(::Nothing) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/StaticLint/src/utils.jl:138
 [2] process(::LanguageServer.JSONRPC.Request{Val{Symbol("julia/getModuleAt")},LanguageServer.TextDocumentPositionParams}, ::LanguageServerInstance) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/LanguageServer/src/requests/features.jl:314
 [3] run(::LanguageServerInstance) at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:251
 [4] top-level scope at /home/pfitzseb/Documents/Git/julia-vscode/scripts/languageserver/main.jl:59
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
```

Not 100% what triggers this though.

### PR DESCRIPTION
**Pull request by ZacLN**
fixes #713 ?

### CODE REVIEW

**Comment by ZacLN** [comment]
Eek, 1 sec

File: src/requests/features.jl [hunk 1]
```diff
@@ -300,11 +300,12 @@ function _binding_kind(b ,server)
     end
 end
 
-function julia_getModuleAt_request(params::TextDocumentPositionParams, server::LanguageServerInstance, conn)
-    doc = getdocument(server, URI2(params.textDocument.uri))
-    offset = get_offset(doc, params.position)
-    x = get_expr1(getcst(doc), offset)
-    return get_module_of(StaticLint.retrieve_scope(x))
+JSONRPC.parse_params(::Type{Val{Symbol("julia/getModuleAt")}}, params) = TextDocumentPositionParams(params)
+function process(r::JSONRPC.Request{Val{Symbol("julia/getModuleAt")},TextDocumentPositionParams}, server)
```
Comment (davidanthoff) [inline src/requests/features.jl:304]: I think that was the wrong merge conflict resolve here :) We want the `function julia_getModuleAt_request(params::TextDocumentPositionParams, server::LanguageServerInstance, conn)` version, and neither `process` nor `parse_params`.
