### PR TITLE
apply_text_edits: make sure indices are computed with updated document.

### LINKED ISSUE #1058: "Your extension just crashed with a bug that we have been trying to replicate for a long time"
The LSP under neovim just crashed on me with the message "LPS[julials] Julia Extension: Please contact us! Your extension just crashed with a bug that we have been trying to replicate for a long time.".

I suppose you will need me to upload some log files? Where do I find them? And what other information do you need?

### PR DESCRIPTION
**Pull request by fredrikekre**
Fixes #1058

### CODE REVIEW

File: src/document.jl [hunk 1]
```diff
@@ -70,11 +70,6 @@ function set_is_workspace_file(doc::Document, value::Bool)
     doc._workspace_file = value
 end
 
-function applytextdocumentchanges(doc::Document, change)
```
Comment (fredrikekre) [inline src/document.jl:73]: This is unused.

**Review by pfitzseb — APPROVED** [review]
