### PR TITLE
fix DataTypeStore field access, closes #635

### LINKED ISSUE #635: type DataTypeStore has no field fields
From [crash reporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%22b0569101-80c4-11ea-b2f9-4b57fb09f756%22%2C%22timestamp%22%3A%222020-04-17T16%3A01%3A09.675Z%22%2C%22cacheId%22%3A%2213e08c4e-7409-417a-b36f-ade8802a4055%22%2C%22eventTable%22%3A%22exceptions%22%7D), I think also caused by the recent changes.

Error message:
```
type DataTypeStore has no field fields 
```

Failed method:
```
getproperty(::SymbolServer.DataTypeStore, ::Symbol)getproperty(::SymbolServer.DataTypeStore, ::Symbol)
```

Stack trace:
```
ErrorException:
   at getproperty(::SymbolServer.DataTypeStore, ::Symbol) (Base.jl33)
   at get_fcall_position(::CSTParser.EXPR, ::String) (./scripts/languageserver/packages/LanguageServer/src/requests/hover.jl97)
   at process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/hover")},LanguageServer.TextDocumentPositionParams}, ::LanguageServerInstance) (./scripts/languageserver/packages/LanguageServer/src/requests/hover.jl8)
   at run(::LanguageServerInstance) (./scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl236)
   at top-level scope (./scripts/languageserver/main.jl28)
   at include(::Module, ::String) (Base.jl377)
   at exec_options(::Base.JLOptions) (client.jl288)
   at _start() (client.jl484)

```

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

File: src/requests/hover.jl [hunk 1]
```diff
@@ -94,8 +94,8 @@ function get_fcall_position(x::EXPR, documentation)
                 documentation = string("Datatype field `$_fieldname` of $(CSTParser.str_value(CSTParser.get_name(dt_ex)))", "\n", documentation)
             elseif StaticLint.hasref(fname) && (refof(fname) isa SymbolServer.DataTypeStore || refof(fname) isa StaticLint.Binding && refof(fname).val isa SymbolServer.DataTypeStore)
                 dts = refof(fname) isa StaticLint.Binding ? refof(fname).val : refof(fname)
-                if length(dts.fields) == call_counts[1] && arg_i <= length(dts.fields)
-                    documentation = string("Datatype field `$(dts.fields[arg_i])`", "\n", documentation)
+                if length(dts.fieldnamess) == call_counts[1] && arg_i <= length(dts.fieldnames)
```
Comment (davidanthoff) [inline src/requests/hover.jl:97]:
```suggestion
                if length(dts.fieldnames) == call_counts[1] && arg_i <= length(dts.fieldnames)
```

File: src/requests/hover.jl [hunk 2]
```diff
@@ -94,8 +94,8 @@ function get_fcall_position(x::EXPR, documentation)
...
+                    documentation = string("Datatype field `$(dts.fieldnamess[arg_i])`", "\n", documentation)
```
Comment (davidanthoff) [inline src/requests/hover.jl:98]:
```suggestion
                    documentation = string("Datatype field `$(dts.fieldnames[arg_i])`", "\n", documentation)
```

Comment (ZacLN) [reply src/requests/hover.jl:98]: Oh my!
